[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.1-alpha.0"
edition = "2021"
authors = ["memothelemo <memothelemo@protonmail.com>"]
license = "AGPL-2.0"
publish = false

[workspace.dependencies]
diesel = { version = "2.1.0", features = ["postgres"] }
