ignore_merge_commits = true

# Credits: https://github.com/cocogitto/cocogitto/blob/main/cog.toml
#
# It can be installed using `cog install-hook --all`
# or alternatively `cog install-hooks {commit_hook_type}
[git_hooks.commit-msg]
script = """#!/bin/sh
set -e

echo "[Check current commit message]"
cog verify --file $1

echo "[Conventional commit check]"
cog check
"""

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "pokepet"
authors = [
	{ signature = "memothelemo", username = "memothelemo" }
]
