use crate::internal::macros::bitflags;

bitflags! {
  pub struct SystemChannelFlags: u8 {
    const SUPPRESS_JOIN_NOTIFICATIONS	= 1 << 0;
    const SUPPRESS_PREMIUM_SUBSCRIPTIONS	= 1 << 1;
    const SUPPRESS_GUILD_REMINDER_NOTIFICATIONS	= 1 << 2;
    const SUPPRESS_JOIN_NOTIFICATION_REPLIES	= 1 << 3;
    const SUPPRESS_ROLE_SUBSCRIPTION_PURCHASE_NOTIFICATIONS	= 1 << 4;
    const SUPPRESS_ROLE_SUBSCRIPTION_PURCHASE_NOTIFICATION_REPLIES = 1 << 5;
  }
}
