name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  commit_check:
    name: Conventional Commit Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup git profile
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions

      - name: Checking commits
        uses: cocogitto/cocogitto-action@v3.5
        with:
          git-user: 'github-actions'
          git-user-email: 'github-actions@github.com'

  tests:
    name: Tests and Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Perform tests
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: --all-features --all-targets --workspace --lcov --output-path lcov.info

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: lcov.info
          fail_ci_if_error: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
